FROM alpine as clone

ENV GIT_REPO=https://github.com/nathancmendoza/notes-archive.git 
ENV SRV_DIR=/srv/notes-archive

RUN apk update && apk add --no-cache git
RUN git clone ${GIT_REPO} ${SRV_DIR}

FROM rust:1.73 as builder

ENV SRV_DIR=/srv/notes-archive

COPY --from=clone ${SRV_DIR} ${SRV_DIR}
RUN cargo install mdbook

WORKDIR ${SRV_DIR}
RUN mdbook build

FROM nginx:alpine

ENV SRV_DIR=/srv/notes-archive
ENV APP_DIR=/app/book

COPY --from=builder ${SRV_DIR}/book ${APP_DIR}
COPY ./static/notesarchive.nginx.conf /etc/nginx/nginx.conf

