FROM alpine as builder

ENV GIT_REPO=https://github.com/nathancmendoza/web-portfolio.git 
ENV APP_DIR=/app/web-portfolio

# Install container dependencies
RUN apk update && apk add --no-cache git npm wget go hugo

# Check out code
RUN git clone ${GIT_REPO} ${APP_DIR}

WORKDIR ${APP_DIR}

# Install site dependencies
RUN npm install 
RUN wget -c https://github.com/hugo-toha/toha/archive/refs/tags/v3.8.0.tar.gz -O - | tar -xz
RUN mv toha-3.8.0/* themes/toha && rm -rf toha-3.8.0/
RUN hugo --minify

FROM nginx:alpine

ENV APP_DIR=/app/web-portfolio
ENV SRV_DIR=/srv/public

# Configure server
COPY --from=builder ${APP_DIR}/public ${SRV_DIR}
COPY ./static/portfolio.nginx.conf /etc/nginx/nginx.conf
